"""Government workflow: assignment, SLA tracking, official 2FA, notifications.

Revision ID: 0002_core
Revises: 0001_core
Create Date: 2026-09-28

Existing tickets are backfilled: their SLA clock is taken to start at creation, and the
node answerable for them is their lowest jurisdiction node (usually the ward).
"""

import sqlalchemy as sa
from alembic import op

revision = '0002_core'
down_revision = '0001_core'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('recipient_type', sa.String(length=16), nullable=False),
    sa.Column('recipient_id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recipient_type IN ('official', 'reporter')", name=op.f('ck_notifications_recipient_type')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_notifications_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_recipient', 'notifications', ['recipient_type', 'recipient_id', 'created_at'], unique=False)
    op.add_column('fix_proofs', sa.Column('accepted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('fix_proofs', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('officials', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('officials', sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tickets', sa.Column('escalated_node_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('assigned_official_id', sa.UUID(), nullable=True))
    op.add_column('tickets', sa.Column('sla_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('sla_warned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('fix_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tickets_assigned_official_id'), 'tickets', ['assigned_official_id'], unique=False)
    op.create_foreign_key(op.f('fk_tickets_escalated_node_id_jurisdictions'), 'tickets', 'jurisdictions', ['escalated_node_id'], ['id'])
    op.create_foreign_key(op.f('fk_tickets_assigned_official_id_officials'), 'tickets', 'officials', ['assigned_official_id'], ['id'])
    # ### end Alembic commands ###
    op.execute("""
        UPDATE tickets
        SET sla_started_at = created_at,
            escalated_node_id = jurisdiction_path[cardinality(jurisdiction_path)]
        WHERE cardinality(jurisdiction_path) > 0
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tickets_assigned_official_id_officials'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_escalated_node_id_jurisdictions'), 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_assigned_official_id'), table_name='tickets')
    op.drop_column('tickets', 'fix_submitted_at')
    op.drop_column('tickets', 'sla_warned_at')
    op.drop_column('tickets', 'sla_started_at')
    op.drop_column('tickets', 'assigned_official_id')
    op.drop_column('tickets', 'escalated_node_id')
    op.drop_column('officials', 'totp_enabled')
    op.drop_column('officials', 'totp_secret')
    op.drop_column('fix_proofs', 'rejection_reason')
    op.drop_column('fix_proofs', 'accepted')
    op.drop_index('ix_notifications_recipient', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
