"""Ticket sightings ("I see this too") and a per-ticket sightings count.

Revision ID: 0003_core
Revises: 0002_core
Create Date: 2026-09-28
"""

import sqlalchemy as sa
from alembic import op

revision = '0003_core'
down_revision = '0002_core'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_sightings',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.String(length=40), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['reporters.reporter_id'], name=op.f('fk_ticket_sightings_reporter_id_reporters')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_sightings_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('ticket_id', 'reporter_id', name=op.f('pk_ticket_sightings'))
    )
    op.add_column('tickets', sa.Column('seen_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'seen_count')
    op.drop_table('ticket_sightings')
    # ### end Alembic commands ###
