"""Security audit log (logins, 2FA, exports, bans, rate-limit hits).

Revision ID: 0004_core
Revises: 0003_core
Create Date: 2026-09-29
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0004_core'
down_revision = '0003_core'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('success', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('ip_hash', sa.String(length=32), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_action_created', 'audit_log', ['action', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_action_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
